site_name: Calendar42 documentation
pages:
- 'Home': 'index.md'
- 'Rest Api':
    - 'Api Tokens': 'rest-api/api-tokens.md'
    - 'Usage': 'rest-api/usage.md'
    - 'objects': 'rest-api/objects.md'
    - 'constants': 'rest-api/constants.md'
    - 'endpoints': 'rest-api/endpoints.md'