site_name: Calendar42 documentation
# make sure you use space indentation!
pages:
- 'Introduction': 'index.md'
- 'Rest Api':
    - 'Introduction': 'rest-api/introduction.md'
    - 'Api Tokens': 'rest-api/api-tokens.md'
    - 'Usage': 'rest-api/usage.md'
    - 'Objects': 'rest-api/objects.md'
    - 'Constants': 'rest-api/constants.md'
    - 'Endpoints':
        - 'Overview': 'rest-api/endpoints.md'
        - 'Events': 'rest-api/endpoints/events.md'
        - 'Calendars': 'rest-api/endpoints/calendars.md'
        - 'Locations': 'rest-api/endpoints/locations.md'
        - 'Event Trip Suggestions': 'rest-api/endpoints/event-trip-suggestions.md'
    - 'Change notes': 'rest-api/change-notes.md'
- 'XMPP API':
    - 'Introduction': 'xmpp-api/introduction.md'
- 'Services':
    - 'Introduction': 'services/introduction.md'
- 'Application Frameworks':
    - 'Introduction': 'application-frameworks/introduction.md'
    - 'C42.js': 'application-frameworks/C42_js.md'
    - 'Native Mobile Component': 'application-frameworks/native_components.md'

docs_dir: "."
theme: readthedocs
site_favicon: favicon.png
extra_css: ["css/extra_css.css"]

# Want to work locally? Clone this repo, create a new virtualenv and..
# 
#   pip install mkdocs
#   mkdocs serve
# 
# Then visit http://localhost:8000/
