pages:
- Home: 'index.md'
- Rest Api: 'rest-api/index.md'
	- 'Api Tokens': 'rest-api/api-tokens.md'
    - 'Usage': 'rest-api/usage.md'
    - 'objects': 'rest-api/objects.md'
    - 'constants': 'rest-api/constants.md'
    - 'endpoints': 'rest-api/endpoints.md'
    - 'Endpoints in development': 'rest-api/endpoints-in-development/index.md'
    	- 'Event Subscriptions': 'rest-api/endpoints-in-development/event-subscriptions.md'
- XMPP API: 'xmpp-api/introduction.md'
- Services: 'services/introduction.md'
- Application Frameworks: 'application-frameworks/introduction.md'
	- C42.js: 'application-frameworks/C42_js.md'
	- Native Mobile Component: 'application-frameworks/native_components.md'