site_name: Calendar42 documentation
# make sure you use space indentation!
pages:
- 'Introduction': 'index.md'
- 'Rest Api':
    - 'Introduction': 'rest-api/introduction.md'
    - 'Api Tokens': 'rest-api/api-tokens.md'
    - 'Usage': 'rest-api/usage.md'
    - 'Objects': 'rest-api/objects.md'
    - 'Constants': 'rest-api/constants.md'
    - 'Endpoints': 'rest-api/endpoints.md'
    - 'Endpoints in development':
        - 'Event Subscriptions': 'rest-api/endpoints-in-development/event-subscriptions.md'
- 'XMPP API':
    - 'Introduction': 'xmpp-api/introduction.md'
- 'Services':
    - 'Introduction': 'services/introduction.md'
- 'Application Frameworks':
    - 'Introduction': 'application-frameworks/introduction.md'
    - 'C42.js': 'application-frameworks/C42_js.md'
    - 'Native Mobile Component': 'application-frameworks/native_components.md'

